version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      FORCE_RENEW: 'false'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: 0
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - https-portal_data:/var/lib/https-portal
  rails:
    context: .
      dockerfile: Dockerfile.prod
    working_dir: /app
    volumes:
      - ./credentials:/app/credentials
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
      DATABASE_HOST: db
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped

volumes:
  https-portal_data:
  db-data:
