name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']

    services:
      mysql:
        image: mysql:8.0.26
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        bundler-cache: true

    - uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "yarn"

    - name: Yarn install
      run: yarn install

    - name: Setup database
      run: |
        sudo /etc/init.d/mysql start
        bundle exec rails db:create
        bundle exec rails db:migrate

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Run RSpec
      run: bundle exec rspec spec
